"""Tests for buildtools-extended sourcing in the qcom setup-env step.

The qcom ``setup_env`` step sources Yocto's buildtools-extended
``environment-setup-*`` script (pinned gcc first on PATH) before the QLI
``setup-environment`` when one is detected, mirroring what host/BYO builds do
via :func:`bakar.diagnostics.detect_buildtools`. PC2 is a rolling-distro host
with a gcc too new for scarthgap, so the pinned toolchain is what makes a qcom
manifest build possible without an Ubuntu container.

These tests exercise the detection outcomes: found via ``BAKAR_BUILDTOOLS_DIR``
(source it before ``setup-environment``), and absent (proceed without it, no
raise), plus the corrected ``build-<distro>`` post-check location. The bare
``subprocess.run`` is mocked at the module-qualified path; assertions inspect
the recorded bash command string and on-disk side effects.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import TYPE_CHECKING
from unittest.mock import MagicMock

import pytest

from bakar.config import (
    DEFAULT_QCOM_MANIFEST,
    DEFAULT_QCOM_REPO_BRANCH,
    DEFAULT_QCOM_REPO_URL,
    BuildConfig,
)
from bakar.steps import qcom_setup_env as qcom_setup_env_step

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

pytestmark = pytest.mark.unit


def _qcom_cfg(workspace: Path) -> BuildConfig:
    """Minimal qcom BuildConfig pointing at a tmp_path workspace."""
    return BuildConfig(
        workspace=workspace,
        bsp_family="qcom",
        machine="exmp-q911",
        distro="qcom-wayland",
        image="qcom-multimedia-image",
        manifest=DEFAULT_QCOM_MANIFEST,
        repo_url=DEFAULT_QCOM_REPO_URL,
        repo_branch=DEFAULT_QCOM_REPO_BRANCH,
        kas_container_image="jetm/kas-build-env:latest",
    )


class _Recorder:
    """Records the argv (and kwargs) of every ``subprocess.run`` call."""

    def __init__(self, side_effect: object = None, returncode: int = 0) -> None:
        self.calls: list[tuple[tuple, dict]] = []
        self._side_effect = side_effect
        self._returncode = returncode

    def __call__(self, *args: object, **kwargs: object) -> MagicMock:
        self.calls.append((args, kwargs))
        if callable(self._side_effect):
            self._side_effect(*args, **kwargs)
        cp = MagicMock()
        cp.returncode = self._returncode
        cp.stdout = ""
        cp.stderr = ""
        return cp

    @property
    def bash_command(self) -> str:
        """The command string from the recorded ``["bash", "-c", <cmd>]`` argv."""
        argv = self.calls[0][0][0]
        return str(argv[2])


class _FakeLogger:
    def __init__(self) -> None:
        self.events: list[tuple[str, str, dict]] = []

    def step_start(self, step: str, **fields: object) -> None:
        self.events.append(("step_start", step, fields))

    def step_ok(self, step: str, **fields: object) -> None:
        self.events.append(("step_ok", step, fields))

    def step_fail(self, step: str, reason: str, **fields: object) -> None:
        self.events.append(("step_fail", step, {"reason": reason, **fields}))

    def info(self, msg: str, **fields: object) -> None:
        self.events.append(("info", msg, fields))


def _drop_bblayers(cfg: BuildConfig) -> Callable[..., None]:
    """subprocess side effect that writes the corrected build-<distro> bblayers.conf."""

    def _side_effect(*args: object, **kwargs: object) -> None:
        cfg.bblayers_conf.parent.mkdir(parents=True, exist_ok=True)
        cfg.bblayers_conf.write_text("# generated by setup-environment\n")

    return _side_effect


def _no_config_buildtools(monkeypatch: pytest.MonkeyPatch) -> None:
    """Clear every buildtools detection source so detect_buildtools is absent."""
    monkeypatch.delenv("OECORE_NATIVE_SYSROOT", raising=False)
    monkeypatch.delenv("BAKAR_BUILDTOOLS_DIR", raising=False)
    monkeypatch.setattr(
        "bakar.diagnostics.load_user_config",
        lambda: SimpleNamespace(buildtools_dir=None, buildtools_dirs={}),
    )


def test_qcom_setup_env_sources_buildtools_before_setup_environment(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A BAKAR_BUILDTOOLS_DIR env script is sourced before ``setup-environment``."""
    qcom = tmp_path / "qcom"
    qcom.mkdir()
    script = qcom / "setup-environment"
    script.write_text("#!/bin/sh\n")

    bt = tmp_path / "buildtools"
    bt.mkdir()
    env_script = bt / "environment-setup-foo"
    env_script.write_text("#!/bin/sh\n")

    # Clear the autouse OECORE so BAKAR_BUILDTOOLS_DIR (detection step 2) is reached.
    monkeypatch.delenv("OECORE_NATIVE_SYSROOT", raising=False)
    monkeypatch.setenv("BAKAR_BUILDTOOLS_DIR", str(bt))

    cfg = _qcom_cfg(tmp_path)
    log = _FakeLogger()
    recorder = _Recorder(side_effect=_drop_bblayers(cfg))
    monkeypatch.setattr(qcom_setup_env_step.subprocess, "run", recorder)

    qcom_setup_env_step.run(cfg, log)

    assert len(recorder.calls) == 1, f"expected one subprocess.run call, got {recorder.calls!r}"
    cmd = recorder.bash_command
    assert str(env_script) in cmd, f"env script not sourced: {cmd!r}"
    assert str(script) in cmd, f"setup-environment not in command: {cmd!r}"
    assert cmd.index(str(env_script)) < cmd.index(str(script)), (
        f"buildtools env script must be sourced before setup-environment: {cmd!r}"
    )


def test_qcom_setup_env_absent_buildtools_proceeds_without_sourcing(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """No toolchain configured -> no buildtools sourced, step still proceeds."""
    qcom = tmp_path / "qcom"
    qcom.mkdir()
    script = qcom / "setup-environment"
    script.write_text("#!/bin/sh\n")

    _no_config_buildtools(monkeypatch)

    cfg = _qcom_cfg(tmp_path)
    log = _FakeLogger()
    recorder = _Recorder(side_effect=_drop_bblayers(cfg))
    monkeypatch.setattr(qcom_setup_env_step.subprocess, "run", recorder)

    qcom_setup_env_step.run(cfg, log)

    assert len(recorder.calls) == 1
    cmd = recorder.bash_command
    assert "environment-setup" not in cmd, f"no buildtools should be sourced: {cmd!r}"
    assert str(script) in cmd, f"setup-environment missing: {cmd!r}"
    assert any(ev[0] == "step_ok" for ev in log.events), f"expected step_ok, got {log.events!r}"


def test_qcom_setup_env_runtimeerror_checks_build_distro_location(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The missing-bblayers post-check must look at build-<distro>, not build/."""
    qcom = tmp_path / "qcom"
    qcom.mkdir()
    (qcom / "setup-environment").write_text("#!/bin/sh\n")

    _no_config_buildtools(monkeypatch)

    cfg = _qcom_cfg(tmp_path)

    # Populate the OLD (wrong) build/ location; the corrected post-check looks at
    # build-qcom-wayland/ and must still raise.
    wrong = qcom / "build" / "conf"
    wrong.mkdir(parents=True)
    (wrong / "bblayers.conf").write_text("# wrong place\n")

    log = _FakeLogger()
    recorder = _Recorder()  # does NOT create the correct bblayers.conf
    monkeypatch.setattr(qcom_setup_env_step.subprocess, "run", recorder)

    with pytest.raises(RuntimeError) as exc_info:
        qcom_setup_env_step.run(cfg, log)

    assert "bblayers.conf" in str(exc_info.value)
    assert str(cfg.bblayers_conf).endswith("build-qcom-wayland/conf/bblayers.conf")
