"""Unit tests for ``generate_dry_run_script`` in ``bakar.steps.kas_build``.

The generator emits a runnable bash script reproducing a build invocation.
Two contracts are verified per workspace family:

- The script parses cleanly under ``bash -n`` (no unescaped ``$``, balanced
  quoting).
- The sync step matches the family: ``repo init``/``repo sync`` for nxp, the
  oe-layertool setup script for ti, and ``kas-container checkout`` for
  bbsetup/generic.

``bash -n`` tests skip when ``bash`` is not on PATH so the suite stays green
on minimal CI images.
"""

from __future__ import annotations

import shutil
import subprocess
from typing import TYPE_CHECKING

import pytest

from bakar.config import BuildConfig
from bakar.steps.kas_build import generate_dry_run_script

if TYPE_CHECKING:
    from pathlib import Path

pytestmark = pytest.mark.unit

_HAS_BASH = shutil.which("bash") is not None
_needs_bash = pytest.mark.skipif(not _HAS_BASH, reason="bash not available")


def _make_cfg(workspace: Path, family: str, manifest: str = "imx-6.12.49-2.2.0.xml") -> BuildConfig:
    """Construct a minimal BuildConfig for ``family`` rooted at ``workspace``."""
    return BuildConfig(
        workspace=workspace,
        bsp_family=family,
        machine="imx95-var-dart",
        distro="fsl-imx-xwayland",
        image="core-image-minimal",
        manifest=manifest,
        repo_url="https://example.invalid/none.git",
        repo_branch="walnascar",
        container_image="jetm/kas-build-env:latest",
    )


def _prepare(workspace: Path, family: str, manifest: str = "imx-6.12.49-2.2.0.xml") -> tuple[BuildConfig, Path, Path]:
    """Build a cfg plus a kas YAML inside bsp_root and an overlay source."""
    cfg = _make_cfg(workspace, family, manifest)
    cfg.bsp_root.mkdir(parents=True, exist_ok=True)
    kas_yaml = cfg.bsp_root / "build.yml"
    kas_yaml.write_text("header: {}\n", encoding="utf-8")
    overlay = workspace / "bakar-tuning.yml"
    overlay.write_text("header: {}\n", encoding="utf-8")
    return cfg, kas_yaml, overlay


def _assert_bash_valid(script: str, tmp_path: Path) -> None:
    """Write the script and assert ``bash -n`` accepts it."""
    path = tmp_path / "out.sh"
    path.write_text(script, encoding="utf-8")
    result = subprocess.run(["bash", "-n", str(path)], capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stderr


def test_header_and_provenance(tmp_path: Path) -> None:
    """The script opens with the shebang, set line, and a bsp_family comment."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "nxp")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    lines = script.splitlines()
    assert lines[0] == "#!/usr/bin/env bash"
    assert lines[1] == "set -euo pipefail"
    assert any(ln == "# bsp_family: nxp" for ln in lines), script
    assert any("Generated by: bakar build --dry-run-script" in ln for ln in lines), script


def test_nxp_sync_step_uses_repo(tmp_path: Path) -> None:
    """An nxp script contains repo init + repo sync, not oe-layertool or checkout."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "nxp")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    assert "repo init" in script, script
    assert "repo sync" in script, script
    assert "kas-container checkout" not in script, script
    assert "oe-layertool-setup.sh" not in script, script


def test_ti_sync_step_uses_layertool(tmp_path: Path) -> None:
    """A ti script invokes the oe-layertool setup script, not repo/checkout."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "ti", "processor-sdk-config_var1.txt")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    assert "oe-layertool-setup.sh" in script, script
    assert "repo init" not in script, script
    assert "kas-container checkout" not in script, script


def test_bbsetup_sync_step_uses_checkout(tmp_path: Path) -> None:
    """A bbsetup script uses kas-container checkout for the sync step."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "bbsetup")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    assert "kas-container checkout" in script, script
    assert "repo init" not in script, script
    assert "oe-layertool-setup.sh" not in script, script


def test_generic_sync_step_uses_checkout(tmp_path: Path) -> None:
    """A generic script also uses kas-container checkout (bbsetup/generic share)."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "generic")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    assert "kas-container checkout" in script, script


def test_build_step_present(tmp_path: Path) -> None:
    """Every family emits a family-agnostic kas-container build step."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "bbsetup")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    assert " build " in script or script.rstrip().endswith("build"), script
    assert "kas-container" in script, script


def test_keep_going_appends_dash_k(tmp_path: Path) -> None:
    """keep_going=True puts ``-- -k`` after the build arg."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "nxp")
    script = generate_dry_run_script(cfg, kas_yaml, overlay, keep_going=True)
    assert "-- -k" in script, script
    assert script.index("build") < script.index("-- -k"), script


def test_no_keep_going_omits_dash_k(tmp_path: Path) -> None:
    """keep_going=False emits no ``-- -k`` suffix."""
    cfg, kas_yaml, overlay = _prepare(tmp_path, "nxp")
    script = generate_dry_run_script(cfg, kas_yaml, overlay, keep_going=False)
    assert "-- -k" not in script, script


def test_dollar_in_env_values_is_literal(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A ``$`` in an exported env value is reproduced literally via single-quoting.

    shlex.quote wraps the value in single quotes where ``$`` is already literal,
    so no further escaping is needed or correct.
    """
    monkeypatch.setenv("BB_NICE_LEVEL_UNUSED", "x")
    monkeypatch.setenv("KAS_EXTRA", "literal-$NOT_EXPANDED-value")
    cfg, kas_yaml, overlay = _prepare(tmp_path, "nxp")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    # shlex.quote produces 'literal-$NOT_EXPANDED-value' — dollar is literal inside single quotes.
    assert "'literal-$NOT_EXPANDED-value'" in script, script
    # Must NOT add a spurious backslash inside the single quotes.
    assert "\\$" not in script, script


@_needs_bash
@pytest.mark.parametrize("family", ["nxp", "ti", "bbsetup", "generic"])
def test_script_passes_bash_n(tmp_path: Path, family: str) -> None:
    """The generated script is syntactically valid for every family."""
    manifest = "processor-sdk-config_var1.txt" if family == "ti" else "imx-6.12.49-2.2.0.xml"
    cfg, kas_yaml, overlay = _prepare(tmp_path, family, manifest)
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    _assert_bash_valid(script, tmp_path)


@_needs_bash
def test_script_passes_bash_n_with_dollar_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A ``$``-bearing env value does not break bash -n once escaped."""
    monkeypatch.setenv("KAS_EXTRA", "a-$b-c")
    cfg, kas_yaml, overlay = _prepare(tmp_path, "bbsetup")
    script = generate_dry_run_script(cfg, kas_yaml, overlay)
    _assert_bash_valid(script, tmp_path)
