"""Host-side integration test for hashserv against the real bitbake-hashserv daemon.

Skips when no bitbake-hashserv is available. Run explicitly with:

    BSPCTL_BITBAKE_HASHSERV=/path/to/bitbake-hashserv \
        uv run pytest tests/integration/test_hashserv_real_daemon.py -v --no-cov
"""

from __future__ import annotations

import os
import shutil
import socket
import stat
import time
from pathlib import Path

import pytest

from bspctl import hashserv


def _find_real_hashserv() -> Path | None:
    candidates: list[Path] = []
    env_override = os.environ.get("BSPCTL_BITBAKE_HASHSERV")
    if env_override:
        candidates.append(Path(env_override))
    candidates.append(Path.home() / "repos" / "personal" / "yocto" / "bitbake" / "bin" / "bitbake-hashserv")
    on_path = shutil.which("bitbake-hashserv")
    if on_path:
        candidates.append(Path(on_path))
    for c in candidates:
        if c.is_file() and os.access(c, os.X_OK):
            return c
    return None


def _install_workspace_binary(workspace: Path, real_binary: Path) -> None:
    """Install a wrapper at ``sources/poky/bitbake/bin/bitbake-hashserv``.

    A bare symlink does not work for two reasons:

    1. ``bitbake-hashserv`` line 17 uses ``__file__`` (not
       ``os.path.realpath(__file__)``) to compute the bitbake ``lib/`` path it
       inserts into ``sys.path``. Through a symlink the computed path is the
       symlink's parent, not the real bitbake checkout's, so ``import hashserv``
       fails.
    2. Under ``uv run`` the ``#!/usr/bin/env python3`` shebang resolves to the
       bspctl venv's interpreter, which lacks the ``websockets`` dependency that
       bitbake's hashserv server pulls in. The system python at
       ``/usr/bin/python3`` has it.

    The wrapper unsets ``VIRTUAL_ENV`` and forces ``PATH=/usr/bin:/bin`` before
    exec'ing the real binary by its absolute path - so the script's internal
    ``__file__`` resolution lands on the real bitbake checkout where ``lib/``
    lives next door.
    """
    workspace_bin_dir = workspace / "sources" / "poky" / "bitbake" / "bin"
    workspace_bin_dir.mkdir(parents=True)
    wrapper = workspace_bin_dir / "bitbake-hashserv"
    wrapper.write_text(
        "#!/usr/bin/env bash\n"
        "# Auto-generated by tests/integration/test_hashserv_real_daemon.py\n"
        "unset VIRTUAL_ENV\n"
        f'PATH=/usr/bin:/bin exec {real_binary} "$@"\n'
    )
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


@pytest.mark.integration
def test_hashserv_real_daemon_lifecycle(tmp_path: Path) -> None:
    """End-to-end: spawn the real daemon, connect TCP, stop it, restart it."""
    real_binary = _find_real_hashserv()
    if real_binary is None:
        pytest.skip(
            "bitbake-hashserv not available - set BSPCTL_BITBAKE_HASHSERV or install yocto/bitbake "
            "at ~/repos/personal/yocto/bitbake/bin/bitbake-hashserv"
        )

    _install_workspace_binary(tmp_path, real_binary)

    # ---- First lifecycle: start, verify, stop ----
    url = hashserv.ensure_running(tmp_path)
    assert url is not None, "ensure_running returned None on a workspace with bitbake-hashserv present"
    assert url.startswith("ws://localhost:"), f"unexpected URL shape: {url}"

    port = int(url.rsplit(":", 1)[1])
    state_dir = tmp_path / ".bspctl"
    pid_file = state_dir / "hashserv.pid"
    port_file = state_dir / "hashserv.port"
    db_file = state_dir / "hashserv.db"

    assert pid_file.is_file(), "PID file was not written"
    assert port_file.is_file(), "port file was not written"
    assert int(port_file.read_text().strip()) == port

    pid = int(pid_file.read_text().strip())
    assert pid > 0

    assert hashserv.is_running(tmp_path) is True

    # Real TCP handshake against the listener - proves the daemon opened its socket.
    with socket.create_connection(("127.0.0.1", port), timeout=2.0) as sock:
        # Successful connect is the end-to-end evidence. Closing immediately is fine.
        assert sock.fileno() > 0

    # ---- Stop and verify cleanup ----
    assert hashserv.stop(tmp_path) is True
    assert not pid_file.exists(), "PID file should be removed on stop"
    assert not port_file.exists(), "port file should be removed on stop"
    # SQLite DB is preserved by design - see spec "SQLite hash database persists ..."
    assert db_file.exists(), "SQLite DB must persist across stop"

    # Daemon takes a tick to actually exit after SIGTERM; poll briefly.
    for _ in range(20):
        if not hashserv.is_running(tmp_path):
            break
        time.sleep(0.1)
    assert hashserv.is_running(tmp_path) is False

    # Capture the inode of the DB before the restart so we can prove it survives.
    db_inode_before = db_file.stat().st_ino

    # ---- Second lifecycle: confirm DB persistence across restart ----
    url2 = hashserv.ensure_running(tmp_path)
    assert url2 is not None, "ensure_running returned None on second start"
    assert url2 == url, "deterministic port: same workspace should derive same port"

    assert db_file.exists(), "SQLite DB must persist across start cycle"
    assert db_file.stat().st_ino == db_inode_before, "SQLite DB inode must be stable across restart"

    # Tear down to leave no orphan daemon.
    assert hashserv.stop(tmp_path) is True
