#!/usr/bin/env python3
"""Generate docs/build-ui.gif via VHS.

Run from the repo root with no arguments to record the GIF:

    uv run python scripts/demo_build_ui.py

VHS invokes this same script in ``--demo`` mode internally to drive the Rich
Live UI inside its virtual terminal. Requirements: vhs, ttyd, ffmpeg,
IosevkaTerm Nerd Font.
"""

from __future__ import annotations

import argparse
import logging
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from rich.console import Console
from rich.live import Live
from rich.logging import RichHandler

from bakar.steps.build_ui import BuildUIState

# VHS tape embedded here so the script is self-contained: it generates
# a temp tape, calls vhs, and vhs re-invokes this script with --demo.
_TAPE = """\
# Generated by scripts/demo_build_ui.py -- do not edit directly.
Output {output}
Require uv

Set Shell "bash"
Set FontFamily "IosevkaTerm Nerd Font"
Set FontSize 18
Set Width 900
Set Height 360
Set Padding 12

Hide
Type "uv run python scripts/demo_build_ui.py --demo"
Enter
Sleep 1400ms
Show
Sleep 13000ms
"""


def _setscene(n: int, total: int = 5944) -> str:
    return f"NOTE: Running setscene task {n} of {total} (/x.bb:do_x_setscene)"


def _task(n: int, total: int = 6000) -> str:
    return f"NOTE: Running task {n} of {total} (/x.bb:do_compile)"


def _start(pf: str, task: str) -> str:
    return f"NOTE: recipe {pf}: task {task}: Started"


def _done(pf: str, task: str) -> str:
    return f"NOTE: recipe {pf}: task {task}: Succeeded"


def _run_demo() -> None:
    """Drive the Rich Live UI with a scripted build sequence (called by VHS)."""
    # Wipe the invoking command line so the recording shows only the UI.
    sys.stdout.write("\x1b[2J\x1b[H")
    sys.stdout.flush()

    console = Console()
    logger = logging.getLogger("demo-build")
    logger.handlers.clear()
    logger.setLevel(logging.INFO)
    logger.addHandler(RichHandler(console=console, show_time=False, show_path=False, markup=True))

    # Backdate bakar start so the global timer reads ~1h02m, consistent with
    # the stuck glibc compile below (a real build that has been running that long).
    ui = BuildUIState(start_monotonic=time.monotonic() - 3750)
    with Live(get_renderable=ui.make_renderable, console=console, refresh_per_second=12, screen=False):
        # --- parse phase: percentage bar ramps to 100% ---
        for pct in (0, 14, 30, 47, 63, 80, 93, 100):
            ui.process_line(f"Parsing recipes: {pct}% || ETA:  0:00:18")
            time.sleep(0.3)
        time.sleep(0.5)

        # --- setscene phase: first counter flips to BUILD ---
        ui.process_line(_setscene(1))
        info = ui.take_pending_log()
        if info:
            logger.info(info)
        ui.process_line(_start("glibc-2.39-r0", "do_unpack_setscene"))
        ui.process_line(_start("openssl-3.2.0-r0", "do_populate_sysroot_setscene"))
        time.sleep(0.5)

        ui.process_line(_setscene(430))
        ui.process_line(_done("glibc-2.39-r0", "do_unpack_setscene"))
        ui.process_line(_done("openssl-3.2.0-r0", "do_populate_sysroot_setscene"))
        ui.process_line(_start("linux-firmware-20240101", "do_fetch_setscene"))
        ui.process_line(_start("python3-3.12.0-r0", "do_compile_setscene"))
        time.sleep(0.4)

        ui.process_line(_setscene(910))
        ui.process_line(_done("linux-firmware-20240101", "do_fetch_setscene"))
        ui.process_line(_done("python3-3.12.0-r0", "do_compile_setscene"))
        time.sleep(0.4)

        # --- tasks phase: first non-setscene counter adds the tasks segment ---
        ui.process_line(_task(1))
        # glibc is the stuck real task: backdate its start way past the run median
        # so it renders in bold red with a drift timer showing how far over it is.
        ui.process_line(_start("glibc-2.39-r0", "do_compile"))
        ui._running["glibc-2.39-r0:do_compile"].start -= 3725
        time.sleep(0.4)

        ui.process_line(_task(50))
        ui.process_line(_start("webkitgtk-2.44.1-r0", "do_compile"))
        ui.process_line(_start("linux-firmware-20240101", "do_fetch"))
        time.sleep(0.5)

        ui.process_line(_task(130))
        ui.process_line(_start("python3-3.12.0-r0", "do_configure"))
        ui.process_line(_start("mesa-24.0.7-r0", "do_package_write_rpm"))
        time.sleep(0.5)

        ui.process_line(_task(430))
        ui.process_line(_done("linux-firmware-20240101", "do_fetch"))
        ui.process_line(_start("gcc-runtime-13.2.0-r0", "do_compile"))
        time.sleep(0.5)

        ui.process_line(_done("python3-3.12.0-r0", "do_configure"))
        ui.process_line(_start("ncurses-6.4-r0", "do_configure"))
        ui.process_line(_task(910))
        time.sleep(0.5)

        ui.process_line(_done("mesa-24.0.7-r0", "do_package_write_rpm"))
        ui.process_line(_start("busybox-1.36.1-r0", "do_compile"))
        ui.process_line(_task(1480))
        time.sleep(0.5)

        # Hold on the final frame so the stuck (red) glibc row is legible. The
        # tape's Sleep 13000ms stops recording during this hold, so the GIF ends
        # on the UI rather than the shell prompt that appears on exit.
        time.sleep(5.0)


def _record() -> None:
    """Write a temp tape and invoke vhs to produce docs/build-ui.gif."""
    repo_root = Path(__file__).resolve().parent.parent
    # VHS Output requires a relative path; use ./ prefix so it resolves
    # unambiguously against cwd=repo_root.
    tape = _TAPE.format(output="./docs/build-ui.gif")
    with tempfile.NamedTemporaryFile(suffix=".tape", mode="w", delete=False, dir=repo_root) as fh:
        fh.write(tape)
        tape_path = Path(fh.name)
    try:
        subprocess.run(["vhs", str(tape_path)], check=True, cwd=repo_root)
    finally:
        tape_path.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--demo", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.demo:
        _run_demo()
    else:
        _record()


if __name__ == "__main__":
    main()
