#!/usr/bin/env python3
"""Generate a native fish completion file for bakar.

Typer 0.26.6 does not support fish via its _BAKAR_COMPLETE mechanism.
This script bypasses Typer's completion system and walks the Click command
tree directly, emitting native fish `complete` commands.

Usage:
    uv run scripts/gen-fish-completion.py > ~/.config/fish/completions/bakar.fish
    cp ~/.config/fish/completions/bakar.fish \\
       ~/.local/share/chezmoi/private_dot_config/fish/completions/bakar.fish
"""

from __future__ import annotations

import sys
from pathlib import Path

import click
import typer

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from bakar.cli import app

cli = typer.main.get_command(app)
prog = "bakar"


def esc(s: str | None) -> str:
    return (s or "").replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").strip()[:80]


def opt_lines(cmd: click.BaseCommand, seen_cmds: tuple[str, ...] = ()) -> list[str]:
    """Yield `complete` lines for a command's options."""
    n = ""
    if seen_cmds:
        cond = " ".join(f"__fish_seen_subcommand_from {c}" for c in seen_cmds)
        n = f"-n '{cond}'"
    result = []
    for param in cmd.params or []:
        if not isinstance(param, click.Option):
            continue
        longs = [o[2:] for o in param.opts if o.startswith("--")]
        shorts = [o[1:] for o in param.opts if o.startswith("-") and len(o) == 2]
        d = esc(param.help)
        parts = [f"complete -c {prog}"]
        if n:
            parts.append(n)
        parts.extend(f"-l {long}" for long in longs)
        parts.extend(f"-s {short}" for short in shorts)
        if not param.is_flag:
            parts.append("-r")
        if d:
            parts.append(f"-d '{d}'")
        result.append(" ".join(parts))
    return result


def gen(cmd: click.BaseCommand, seen: tuple[str, ...] = ()) -> list[str]:
    """Recursively generate completions for a command and all subcommands."""
    if not isinstance(cmd, click.Group):
        return opt_lines(cmd, seen)

    ctx = click.Context(cmd)
    child_names = list(cmd.list_commands(ctx))

    if not seen:
        guard = "not __fish_seen_subcommand_from " + " ".join(child_names)
    else:
        guard = " ".join(f"__fish_seen_subcommand_from {c}" for c in seen)
        guard += "; and not __fish_seen_subcommand_from " + " ".join(child_names)

    out = []
    for name in child_names:
        sub = cmd.get_command(ctx, name)
        d = esc(sub.help if sub else "")
        line = f"complete -c {prog} -n '{guard}' -a {name}"
        if d:
            line += f" -d '{d}'"
        out.append(line)

    for name in child_names:
        sub = cmd.get_command(ctx, name)
        if sub is None:
            continue
        out.append(f"# {' '.join((*seen, name))}")
        out.extend(opt_lines(sub, (*seen, name)))
        if isinstance(sub, click.Group):
            out.extend(gen(sub, (*seen, name)))

    return out


lines = [
    f"# {prog} fish completions — generated by scripts/gen-fish-completion.py",
    "# Regenerate after adding new commands:",
    "#   uv run scripts/gen-fish-completion.py > ~/.config/fish/completions/bakar.fish",
    "#   cp ~/.config/fish/completions/bakar.fish \\",
    "#      ~/.local/share/chezmoi/private_dot_config/fish/completions/bakar.fish",
    "",
    f"complete -e -c {prog}",
    f"complete -c {prog} -f",
    "",
    "# preset names — bakar's console writes to stderr, so capture 2>&1;",
    "# then keep only tokens that look like preset names (alphanum + dash/underscore)",
    "function _bakar_preset_names",
    "    set -l raw (bakar presets list 2>&1 | string replace -r '\\s.*' '')",
    "    set -l presets (string match -r '^[a-zA-Z0-9][a-zA-Z0-9_-]*$' $raw)",
    "    if set -q presets[1]",
    "        printf '%s\\n' $presets",
    "    else",
    "        echo '(no presets defined — run: bakar presets add)'",
    "    end",
    "end",
    "",
    "# global options",
]
lines.extend(opt_lines(cli))
lines.append("")
lines.extend(gen(cli))

result = "\n".join(lines)
# --preset takes dynamic completions from the preset list, not a plain string
result = result.replace(
    "-n '__fish_seen_subcommand_from build' -l preset -r",
    "-n '__fish_seen_subcommand_from build' -l preset -xa '(_bakar_preset_names)'",
)
print(result)
